before_script:
  - npm config set registry http://122.144.216.10:4873/
  - npm ci --cache .npm --prefer-offline

cache:
  key: npm-cache
  paths:
    - .npm/

stages:
  - deploy

.deploy:
  stage: deploy
  script:
    - ssh -p 60022 root@122.144.216.10 "rm -rf /usr/local/nginx/html/pro-components/*"
    - scp -P 60022 -r projects/ui-docs/docs/.vitepress/dist/* root@122.144.216.10:/usr/local/nginx/html/pro-components

deploy-by-message:
  extends: .deploy
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /deploy/

deploy-manual:
  extends: .deploy
  when: manual
